### ISSUE TITLE
Multiple namespaces

### ISSUE THREAD

**Issue by webbedspace** [oneuijs/oui-dom-events#1]
This library currently doesn't support multiple namespaces - for instance, something like `on(window, "mousemove.myUI.myModule" will create a namespace called "myUI.myModule", preventing me from calling`off(window, 'mousemove.myUI')` to remove all events with the "myUI" namespace and any additional namespaces. This was a common feature of Zepto/jQuery's event API.

Is this planned to be added at some point?

**Comment by camsong** [comment]
Namespace is already supported, see  the description under title 'DOM events manager with namespace support'

**Comment by webbedspace** [comment]
This only supports one namespace per handler, though - I want to know if I can put a _single_ event handler into _multiple_ namespaces.
