### ISSUE TITLE
off() using just a namespace

### ISSUE THREAD

**Issue by webbedspace** [oneuijs/oui-dom-events#2]
Consider this example code:

```
const button1 = document.getElementById("#button1");

Events.on(button1, "mousedown.namespace", ()=>console.log('down'));
Events.on(button1, "mouseup.namespace", ()=>console.log('up'));
```

The following line does _not_ work:

```
Events.off(button1, ".namespace");
```

What this should do (as it does in Zepto and jQuery) is remove both of the attached events. Instead it does nothing.

**Comment by camsong** [comment]
Good point, sorry I misunderstood you before, will add this feature later. You can also raise a PR if you have time 😸
